DROP DATABASE IF EXISTS polynames;
   
CREATE DATABASE PolyNames ;
USE PolyNames ;

CREATE TABLE `Joueur`(
	`Pseudo` VARCHAR(50) NOT NULL,
	`Role` VARCHAR(50) NOT NULL,
	`IDEquipe` INT NOT NULL,
	`IDPartie` INT NOT NULL,
	`IDJoueur` INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(`IDJoueur`)
);

CREATE TABLE `Equipe`(
	`Nom` VARCHAR(25) NOT NULL,
	`Points` INT DEFAULT 0,
	`IDPartie` INT NOT NULL,
	`IDEquipe` INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(`IDEquipe`)
);

CREATE TABLE `Partie`(
	`Code` VARCHAR(8) NOT NULL,
	`Etat` VARCHAR(25) NOT NULL,
	`IDPartie` INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(`IDPartie`)
);

CREATE TABLE `Carte`(
	`Nom` VARCHAR(50) NOT NULL,
	`IDCarte` INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(`IDCarte`)
);

CREATE TABLE `CarteJouee`(
	`Couleur` VARCHAR(10) NOT NULL,
	`IDCarte` INT NOT NULL,
	`IDPartie` INT NOT NULL,
	PRIMARY KEY(`IDCarte`, `IDPartie`)
);


ALTER TABLE `Joueur`
ADD CONSTRAINT `FK_Joueur_Equipe`
FOREIGN KEY (`IDEquipe`)
REFERENCES `Equipe`(`IDEquipe`)
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE `Joueur`
ADD CONSTRAINT `FK_Joueur_Partie`
FOREIGN KEY (`IDPartie`)
REFERENCES `Partie`(`IDPartie`)
ON UPDATE NO ACTION
ON DELETE NO ACTION;


ALTER TABLE `Equipe`
ADD CONSTRAINT `FK_Equipe_Partie`
FOREIGN KEY (`IDPartie`)
REFERENCES `Partie`(`IDPartie`)
ON UPDATE NO ACTION
ON DELETE NO ACTION;


ALTER TABLE `CarteJouee`
ADD CONSTRAINT `FK_CarteJouee_Partie`
FOREIGN KEY (`IDPartie`)
REFERENCES `Partie`(`IDPartie`)
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE `CarteJouee`
ADD CONSTRAINT `FK_CarteJouee_Carte`
FOREIGN KEY (`IDCarte`)
REFERENCES `Carte`(`IDCarte`)
ON UPDATE NO ACTION
ON DELETE NO ACTION;